version: "3.9"

services:
  etl:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: fuel_etl
    env_file:
      - ../.env
    volumes:
      - ../data:/app/data
    command: python -m src.producer